In [1]:
a = list(range(1000))

In [4]:
%timeit [i**2 for i in a]

629 µs ± 86.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
import numpy as np

In [6]:
arr = np.array(a)

In [9]:
%timeit arr**2

4.08 µs ± 975 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Functions in Numpy

In [79]:
arr = np.random.randint(10,100, size=(5,4))

In [24]:
arr.shape

(5, 4)

In [23]:
arr

array([[69, 45, 38, 23],
       [27, 36, 15, 93],
       [52, 18, 66, 35],
       [99, 76, 31, 19],
       [22, 88, 60, 67]])

In [18]:
np.sum(arr)

979

In [19]:
np.mean(arr)

48.95

In [27]:
np.sum(arr, axis=0)

array([269, 263, 210, 237])

In [32]:
arr_3d = np.random.randint(1, 10, size=(3,2,4))

In [34]:
arr_3d.shape

(3, 2, 4)

In [40]:
arr_3d

array([[[2, 4, 4, 1],
        [9, 9, 1, 3]],

       [[8, 2, 2, 5],
        [6, 3, 6, 3]],

       [[8, 8, 6, 7],
        [2, 4, 4, 8]]])

In [38]:
np.sum(arr_3d, axis=0)

array([[18, 14, 12, 13],
       [17, 16, 11, 14]])

In [39]:
np.sum(arr_3d, axis=-1)

array([[11, 22],
       [17, 18],
       [29, 18]])

# Masking

In [47]:
arr>50

array([[ True, False, False, False],
       [False, False, False,  True],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [False,  True,  True,  True]])

In [48]:
new_arr = np.random.randint(1, 100, size=30)

In [49]:
new_arr

array([97, 70, 82, 89, 26, 18, 27, 57, 12, 15, 95, 46, 23,  4,  7, 14, 34,
       64, 29, 23, 65, 91, 89, 81, 61, 54, 12, 86, 88, 99])

In [53]:
mask = new_arr>50
mask

array([ True,  True,  True,  True, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True])

In [54]:
new_arr[mask]

array([97, 70, 82, 89, 57, 95, 64, 65, 91, 89, 81, 61, 54, 86, 88, 99])

In [55]:
new_arr[new_arr>50]

array([97, 70, 82, 89, 57, 95, 64, 65, 91, 89, 81, 61, 54, 86, 88, 99])

In [57]:
new_arr[new_arr%2==0]

array([70, 82, 26, 18, 12, 46,  4, 14, 34, 64, 54, 12, 86, 88])

In [68]:
arr[:2, :2] = 0

In [69]:
arr

array([[ 0,  0, 38, 23],
       [ 0,  0, 15, 93],
       [52, 18, 66, 35],
       [99, 76, 31, 19],
       [22, 88, 60, 67]])

In [70]:
new_arr

array([97, 70, 82, 89, 26, 18, 27, 57, 12, 15, 95, 46, 23,  4,  7, 14, 34,
       64, 29, 23, 65, 91, 89, 81, 61, 54, 12, 86, 88, 99])

In [81]:
np.max(arr)

96

In [82]:
np.min(arr)

10

In [83]:
np.max(arr, axis=0)

array([77, 68, 96, 81])

In [84]:
np.min(arr, axis =1)

array([29, 41, 30, 22, 10])

In [91]:
new_arr.argmax()

29

In [93]:
np.argmin(new_arr)

13

In [92]:
new_arr[29]

99

In [94]:
new_arr[13]

4

### Reshape

In [108]:
arr

array([[29, 43, 96, 81],
       [77, 68, 58, 41],
       [49, 68, 68, 30],
       [22, 52, 55, 75],
       [10, 31, 76, 76]])

In [109]:
arr.shape

(5, 4)

In [115]:
np.reshape(arr, newshape=(-1,5))

array([[29, 43, 96, 81, 77],
       [68, 58, 41, 49, 68],
       [68, 30, 22, 52, 55],
       [75, 10, 31, 76, 76]])

In [123]:
a = np.arange(10)

In [124]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
b = a.copy()

In [126]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
a[:5] = 999

In [128]:
a

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9])

In [129]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Vectorization

In [130]:
pA = np.array([2,3])
pB = np.array([5,4])

In [133]:
def distance(pA, pB):
    return np.sum( (pB - pA)**2 )**0.5

In [134]:
distance(pA, pB)

3.1622776601683795

In [136]:
np.transpose(arr)

array([[29, 77, 49, 22, 10],
       [43, 68, 68, 52, 31],
       [96, 58, 68, 55, 76],
       [81, 41, 30, 75, 76]])

In [137]:
arr.T

array([[29, 77, 49, 22, 10],
       [43, 68, 68, 52, 31],
       [96, 58, 68, 55, 76],
       [81, 41, 30, 75, 76]])

In [140]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [142]:
#np.linalg.inv(arr)

In [143]:
np.sin(0)

0.0

In [144]:
np.sin(90)

0.8939966636005579