In [3]:
#pip install numpy

In [5]:
import numpy as np

In [6]:
l1 = [1,2,3,4]

In [7]:
type(l1)

list

In [9]:
arr = np.array(l1)

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr

array([1, 2, 3, 4])

In [13]:
arr.shape

(4,)

In [14]:
arr.ndim

1

In [38]:
arr2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype='float')

In [39]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [31]:
arr2.ndim

2

In [32]:
arr2.shape

(3, 3)

In [40]:
arr2.dtype

dtype('float64')

In [41]:
l = range(10)

In [56]:
a = np.array(l)

In [48]:
%timeit np.array(l**2)*100

10.1 µs ± 213 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [53]:
import timeit

In [62]:
%timeit [i**2 for i in l]

4.17 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [59]:
%timeit a**2

1.19 µs ± 24 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [67]:
arr

array([1, 2, 3, 4])

In [65]:
# all ele added by 4
arr+4

array([5, 6, 7, 8])

In [66]:
arr*4

array([ 4,  8, 12, 16])

In [68]:
arr -3  

array([-2, -1,  0,  1])

In [74]:
arr1 = np.array([2,3,4,5])

In [75]:
# element wise additon
arr + arr1

array([3, 5, 7, 9])

In [79]:
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [78]:
arr2 + 2

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

### Random

In [135]:
arr1 = np.random.randint(10, 100, size = (5,5))
arr2 = np.random.randint(10, 100, size = (5,5))

In [136]:
arr1

array([[92, 34, 38, 97, 73],
       [23, 36, 52, 57, 51],
       [80, 71, 17, 30, 38],
       [13, 81, 37, 29, 83],
       [28, 20, 40, 83, 83]])

In [137]:
arr2

array([[54, 20, 81, 54, 75],
       [94, 30, 88, 26, 25],
       [29, 61, 12, 12, 39],
       [78, 89, 12, 17, 94],
       [45, 66, 52, 73, 57]])

###### Operations on Matrix

In [140]:
arr1 + arr2

array([[146,  54, 119, 151, 148],
       [117,  66, 140,  83,  76],
       [109, 132,  29,  42,  77],
       [ 91, 170,  49,  46, 177],
       [ 73,  86,  92, 156, 140]])

In [144]:
# element wise multiplication
arr1 * arr2

array([[4968,  680, 3078, 5238, 5475],
       [2162, 1080, 4576, 1482, 1275],
       [2320, 4331,  204,  360, 1482],
       [1014, 7209,  444,  493, 7802],
       [1260, 1320, 2080, 6059, 4731]])

In [145]:
arr1 ** 2

array([[92, 34, 38, 97, 73],
       [23, 36, 52, 57, 51],
       [80, 71, 17, 30, 38],
       [13, 81, 37, 29, 83],
       [28, 20, 40, 83, 83]])

In [150]:
# element wise square
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [154]:
# MATRIX MULTIPLICATION
np.dot(arr1, arr2)

array([[20117, 18629, 15860, 13286, 22511],
       [12875, 13151,  8991,  7494, 12918],
       [15537,  9945, 15268,  9654, 13424],
       [15386, 13006, 13289,  9804, 11900],
       [14761, 16465,  9820,  9982, 16693]])

In [158]:
arr1.dot(arr2)

array([[20117, 18629, 15860, 13286, 22511],
       [12875, 13151,  8991,  7494, 12918],
       [15537,  9945, 15268,  9654, 13424],
       [15386, 13006, 13289,  9804, 11900],
       [14761, 16465,  9820,  9982, 16693]])

# Array Slicing

In [161]:
arr1*arr2

array([[4968,  680, 3078, 5238, 5475],
       [2162, 1080, 4576, 1482, 1275],
       [2320, 4331,  204,  360, 1482],
       [1014, 7209,  444,  493, 7802],
       [1260, 1320, 2080, 6059, 4731]])

In [162]:
arr1

array([[92, 34, 38, 97, 73],
       [23, 36, 52, 57, 51],
       [80, 71, 17, 30, 38],
       [13, 81, 37, 29, 83],
       [28, 20, 40, 83, 83]])

In [167]:
arr1[3,2]

37

In [168]:
# arr[ rows , cols]
arr1[ 1:4 , 1 : 5 ]

array([[36, 52, 57, 51],
       [71, 17, 30, 38],
       [81, 37, 29, 83]])

In [171]:
arr1[ : , 1:3]

array([[34, 38],
       [36, 52],
       [71, 17],
       [81, 37],
       [20, 40]])

In [173]:
# also pass list of indexes
arr1[ [1,3,4] , :4 ]

array([[23, 36, 52, 57],
       [13, 81, 37, 29],
       [28, 20, 40, 83]])

# BroadCasting

In [181]:
arr1[:, :4]

array([[92, 34, 38, 97],
       [23, 36, 52, 57],
       [80, 71, 17, 30],
       [13, 81, 37, 29],
       [28, 20, 40, 83]])

In [182]:
arr1[1, :4]

array([23, 36, 52, 57])

In [184]:
np.array([[1,2,3],[4,5,6],[7,8,9]]) + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [187]:
np.zeros((5,))

array([0., 0., 0., 0., 0.])

In [189]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [194]:
np.full((5,4), fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [195]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [197]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [201]:
np.arange(33, 100, 2)

array([33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65,
       67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [202]:
np.linspace(start=1, stop = 2, num=50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])